<?php
/**
 * Created by PhpStorm.
 * User: gabe3
 * Date: 4/11/2019
 * Time: 4:02 PM
 */

function dbtng_custom_entry_insert($entry) {
    $return_value = NULL;
    try {
        $return_value = db_insert('dbtng_custom')
            ->fields($entry)
            ->execute();
    }
    catch (Exception $e) {
        drupal_set_message(t('db_insert failed. Message = %message, query= %query',
            array('%message' => $e->getMessage(), '%query' => $e->query_string)), 'error');
    }
    return $return_value;
}

function dbtng_custom_entry_update($entry) {
    try {
        // db_update()...->execute() returns the number of rows updated.
        $count = db_update('dbtng_custom')
            ->fields($entry)
            ->condition('pid', $entry['pid'])
            ->execute();
    }
    catch (Exception $e) {
        drupal_set_message(t('db_update failed. Message = %message, query= %query',
            array('%message' => $e->getMessage(), '%query' => $e->query_string)), 'error');
    }
    return $count;
}

function dbtng_custom_entry_delete($entry) {
    db_delete('dbtng_custom')
        ->condition('pid', $entry['pid'])
        ->execute();

}


function dbtng_custom_entry_load($entry = array()) {
    // Read all fields from the dbtng_example table.
    $select = db_select('dbtng_custom', 'custom');
    $select->fields('custom');

    // Add each field and value as a condition to this query.
    foreach ($entry as $field => $value) {
        $select->condition($field, $value);
    }
    // Return the result in object format.
    return $select->execute()->fetchAll();
}


